#!/bin/bash

BUS=""
CACHE_FILE="/tmp/monitor_i2c_bus"
LEVELS=( 0 10 16 24 32 42 50 64 80 100 )

# Check whether monitor is on before querying any info
xset q | grep "Monitor is On" > /dev/null || exit 0

probe_device () {
    BUS=$(ddcutil -t detect 2> /dev/null | awk '/I2C bus/{print substr($3,10)}')
    if ! check_device; then
        return 1
    fi
    echo -n "$BUS" > $CACHE_FILE
    return 0
}

read_cache () {
    [ -f "$CACHE_FILE" ] || return 1
    BUS=$(cat $CACHE_FILE)
    check_device
}

check_device () {
    [ -n "/dev/i2c-$BUS" -a -c "/dev/i2c-$BUS" ]
}

get_brightness () {
    ddcutil -t -b $BUS getvcp 0x10 | awk '{print $4}'
}

set_brightness () {
    ddcutil --noverify -b $BUS setvcp 0x10 $1
}

read_cache || probe_device || exit 1

BRIGHTNESS=$(get_brightness)

case "$1" in
    get)
        echo $BRIGHTNESS
        ;;
    raise)
        for i in $(seq 0 9); do
            LEVEL=${LEVELS[$i]}
            if [ $LEVEL -gt $BRIGHTNESS ]; then
                set_brightness $LEVEL
                exit 0
            fi
        done
        ;;
    lower)
        for i in $(seq 9 -1 0); do
            LEVEL=${LEVELS[$i]}
            if [ $LEVEL -lt $BRIGHTNESS ]; then
                set_brightness $LEVEL
                exit 0
            fi
        done
        ;;
    *)
        echo "Illegal argument"
        exit 1
        ;;
esac
