#!/bin/sh
PLAYER=$(playerctl -a metadata --format '{{playerName}}|{{xesam:title}}' | awk -F'|' '{ if ($2 != "") { printf $1; exit } }')

if [[ -n "$PLAYER" ]]; then
    playerctl -p $PLAYER metadata --format '{{xesam:artist}} ・ {{xesam:title}}'
else
    echo ""
fi
