#!/bin/sh
PLAYER=$(playerctl -s -a metadata --format '{{playerName}}|{{xesam:title}}' | awk -F'|' '{ if ($2 != "") { printf $1; exit } }')

if [[ -n "$PLAYER" ]]; then
    playerctl -s -p $PLAYER metadata --format '{{xesam:artist}} ・ {{xesam:title}}' | awk 'length > 100{$0=substr($0,0,101)"..."}1'
else
    echo ""
fi
