#!/usr/bin/fish
function bt_status
    return (bluetoothctl show | awk '/Powered: /{ exit $2 == "no"}')
end

if test "$BLOCK_BUTTON" = "1"
    if bt_status
        bluetoothctl power off > /dev/null
    else
        bluetoothctl power on > /dev/null
    end
end

echo -n "BT: "
if bt_status
    echo "on"
else
    echo "off"
end
