#!/bin/sh
ARTIST="$(playerctl metadata xesam:artist)"
TITLE="$(playerctl metadata xesam:title)"
STRING="$ARTIST - $TITLE"

if [ -n "$TITLE" ]; then
    echo "$STRING"
    echo "$STRING"
    echo "#1DB954"
fi

if [ -n "$BLOCK_BUTTON" ] && [ $BLOCK_BUTTON -eq 1 ]; then
    playerctl play-pause
fi

