#!/bin/bash
# Displays the default device, volume, and mute status for i3blocks

############################################################
# Taken from vivien/i3blocks-contrib, modified by Maxr1998 #
############################################################
# See  https://github.com/vivien/i3blocks-contrib/blob/master/volume-pulseaudio/volume-pulseaudio

AUDIO_INTERVAL=5

DEFAULT_COLOR="#ffffff"
MUTED_COLOR="#a0a0a0"

LONG_FORMAT=0
SHORT_FORMAT=2
USE_ALSA_NAME=0
USE_DESCRIPTION=0

SUBSCRIBE=0

VOLUME_SCRIPT=$SCRIPT_DIR/../i3-volume/volume

function slog {
    >&2 echo "VOLUME-LOG: $@"
}

case "$BLOCK_BUTTON" in
    1) $VOLUME_SCRIPT -mn ;; 
    2) ;;
    3) $SCRIPT_DIR/../utils/audio_settings > /dev/null ;;
    4) $VOLUME_SCRIPT -i 5 ;;
    5) $VOLUME_SCRIPT -d 5 ;;
esac

function print_format {
    PERCENT="%"
    case "$1" in
        1) echo "$VOL$PERCENT [$NAME]" ;;
        2) echo "$VOL$PERCENT [$INDEX]";;
        3) echo "$VOL$PERCENT" ;;
        *) echo "$VOL$PERCENT [$INDEX:$NAME]" ;;
    esac
}

function print_block {
    for name in INDEX NAME VOL MUTED; do
        read $name
    done < <(pacmd list-sinks | grep "index:\|name:\|volume: front\|muted:" | grep -A3 '*')
    INDEX=$(echo "$INDEX" | grep -o '[0-9]\+')
    VOL=$(echo "$VOL" | grep -o "[0-9]*%" | head -1 )
    VOL="${VOL%?}"

    NAME=$(echo "$NAME" | sed \
's/.*<.*\.\(.*\)>.*/\1/; t;'\
's/.*<\(.*\)>.*/\1/; t;'\
's/.*/unknown/')

    if [[ $USE_ALSA_NAME == 1 ]] ; then
        ALSA_NAME=$(pacmd list-sinks |\
awk '/^\s*\*/{f=1}/^\s*index:/{f=0}f' |\
grep "alsa.name\|alsa.mixer_name" |\
head -n1 |\
sed 's/.*= "\(.*\)".*/\1/')
        NAME=${ALSA_NAME:-$NAME}
    elif [[ $USE_DESCRIPTION == 1 ]] ; then
        DESCRIPTION=$(pacmd list-sinks |\
awk '/^\s*\*/{f=1}/^\s*index:/{f=0}f' |\
grep "device.description" |\
head -n1 |\
sed 's/.*= "\(.*\)".*/\1/')
        NAME=${DESCRIPTION:-$NAME}
    fi

    if [[ $MUTED =~ "no" ]] ; then
        COLOR=$DEFAULT_COLOR
    else
        COLOR=$MUTED_COLOR
    fi

    if [[ $SUBSCRIBE == 1 ]] ; then
        print_format "$LONG_FORMAT"
    else
        print_format "$LONG_FORMAT"
        print_format "$SHORT_FORMAT"
        echo "$COLOR"
    fi
}

print_block
if [[ $SUBSCRIBE == 1 ]] ; then
    while read -r EVENT; do
        print_block
    done < <(pactl subscribe | stdbuf -oL grep change)
fi
