profile=high-quality
vo=gpu-next
hwdec=auto
volume=42
sub-margin-y=12
sub-font-size=42
sub-back-color='#99000000'
sub-border-style=background-box
sub-border-color='#33000000'
sub-border-size=1
audio-display=no

# Cache settings
cache=yes
demuxer-max-bytes=500MiB

# Screenshot settings
screenshot-format=png
screenshot-webp-lossless=yes
screenshot-webp-compression=6

[deinterlace]
profile-cond=p["video-frame-info/tff"]
profile-restore=copy
hwdec=no
vf=bwdif
