#!/bin/sh
GPU_PATH=/sys/class/drm/card0/device

{
    awk '{ print "GPU Load:_" $0"%" }' $GPU_PATH/gpu_busy_percent
    awk '/*/{ print "SoC Clock:_" $2 }' $GPU_PATH/pp_dpm_sclk
    awk '/*/{ print "Memory Clock:_" $2 }' $GPU_PATH/pp_dpm_mclk
    sensors | awk '/junction/{ print "Junction Temp:_" $2 }'
    sensors | awk '/mem/{ print "Memory Temp:_" $2 }'
    sensors | awk '/power1/{ print "Power:_" $2 "W" }'
} | column -t -s "_"
