#!/bin/bash
GPU_PATH=/sys/class/drm/card0/device
PP_CLK_VOLTAGE_TABLE=$GPU_PATH/pp_od_clk_voltage

CORE_CLOCKS=(
    "s 0 852 800"
    "s 1 991 900"
    "s 2 1138 920"
    "s 3 1269 940"
    "s 4 1312 950"
    "s 5 1474 960"
    "s 6 1592 975"
    "s 7 1656 990"
)

MEMORY_CLOCKS=(
    "m 0 167 800"
    "m 1 500 800"
    "m 2 700 870"
    "m 3 925 900"
)

POWER_CAP_W="220"

# Check if root
if [[ $EUID -ne 0 ]]; then
   echo "Insufficient permissions..."
   exit 1
fi

# Enable manual setup
echo "manual" > $GPU_PATH/power_dpm_force_performance_level

# Set core and memory clocks
for clk in "${CORE_CLOCKS[@]}"; do
    echo "$clk" > $PP_CLK_VOLTAGE_TABLE
done
for clk in "${MEMORY_CLOCKS[@]}"; do
    echo "$clk" > $PP_CLK_VOLTAGE_TABLE
done

# Commit changes
echo "c" > $PP_CLK_VOLTAGE_TABLE

# Set power cap
echo "${POWER_CAP_W}000000" > $GPU_PATH/hwmon/hwmon*/power1_cap

# Enable all P-states
echo "0 1 2 3 4 5 6 7" > $GPU_PATH/pp_dpm_sclk

# Enable all memory states
echo "0 1 2 3" > $GPU_PATH/pp_dpm_mclk

# Print results
echo -e "\nAll settings applied.\n" && cat $PP_CLK_VOLTAGE_TABLE
