#!/bin/sh
pgrep -x "i3" > /dev/null || exit 0

# Debounce keys
sleep 0.4 

echo "Locking screen"

# Display options
xset dpms force off
xset dpms 0 0 10

# Locking
W="ffffffff"
B="00000000"

MARGIN=80

i3lock -n -t -i "$HOME/Bilder/Wallpapers/Lockscreen.png" \
    --ring-color=$W --separator-color=$B --line-uses-inside \
    --keyhl-color=d23c3dff --bshl-color=d23c3dff \
    --ringver-color=$W --ringwrong-color=$W \
    --inside-color=373445ff --insidever-color=fecf4dff --insidewrong-color=d23c3dff \
    --indicator --force-clock \
    --ind-pos="x+$MARGIN:y+h-$MARGIN" --radius=14 --ring-width=2.5 \
    --time-pos="x+$MARGIN+24:y+h-$MARGIN+12" --time-align=1 --time-color=$W \
    --date-str="" --verif-text="" --wrong-text="" --noinput-text=""

echo "Screen unlocked"

# Display options
xset dpms 0 0 1800
# EOF
