# vim: set filetype=swayconfig

# Application launcher
bindsym $mod+d exec --no-startup-id j4-dmenu-desktop --usage-log="$HOME/.cache/dmenu_usage.log" --use-xdg-de --no-generic --dmenu="rofi -dmenu -i -window-title 'Anwendung' -dpi 0"
# Raw command runner
bindsym $mod+x exec --no-startup-id rofi -dmenu -i -window-title 'cmd' -theme-str 'listview { lines: 0; }' | xargs -r swaymsg exec
# Start a terminal
bindsym Control+$mod+T exec wezterm

# Clipboard history
bindsym $mod+c exec --no-startup-id cliphist list | rofi -dmenu -p 'Verlauf durchsuchen' -display-columns 2 | cliphist decode | wl-copy

# Notification center
bindsym $mod+Shift+n exec swaync-client -t -sw

# Emoji picker
bindsym $mod+e exec --no-startup-id rofimoji

# Power key/lock setup
bindsym XF86PowerOff exec --no-startup-id ~/.config/sway/utils/lock && ~/.config/sway/utils/sleep
bindsym Mod4+l exec --no-startup-id ~/.config/sway/utils/lock && ~/.config/sway/utils/sleep

# Power menu
bindsym $mod+Shift+e exec --no-startup-id shutdown-dialog

# Media keys
set $audio ~/.local/lib/audio
bindsym XF86AudioRaiseVolume exec --no-startup-id $audio raise
bindsym XF86AudioLowerVolume exec --no-startup-id $audio lower
bindsym XF86AudioMute exec --no-startup-id $audio mute

#bindsym XF86AudioPlay exec playerctl --player=playerctld play
#bindsym XF86AudioPause exec playerctl --player=playerctld pause
bindsym XF86AudioNext exec playerctl --player=playerctld next
bindsym XF86AudioPrev exec playerctl --player=playerctld previous

# Macropad
bindcode 196 exec playerctl --player=playerctld volume 0.02-
bindcode 197 exec playerctl --player=playerctld volume 0.02+
bindcode 198 exec playerctl --player=playerctld play-pause

# Brightness
bindsym XF86MonBrightnessUp exec --no-startup-id notify-send -i "weather-clear" -h string:synchronous:volume -h int:value:"$(brightnessctl set +5% | awk '/\(/{print $4}' | tr -d '(' | tr -d '%)')" "Helligkeit"
bindsym XF86MonBrightnessDown exec --no-startup-id notify-send -i "weather-clear" -h string:synchronous:volume -h int:value:"$(brightnessctl set 5%- | awk '/\(/{print $4}' | tr -d '(' | tr -d '%)')" "Helligkeit"

# Screenshot
bindsym Control+Print exec --no-startup-id flameshot gui

# Reload the configuration file
bindsym $mod+Shift+c reload