# vim: set filetype=swayconfig

# GNOME setup
exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Run XDG autostart entries
exec dex -ae i3

# Lock on sleep
exec --no-startup-id swayidle -w before-sleep '~/.config/sway/utils/lock'

# IME
exec --no-startup-id fcitx5

# Clipboard manager
exec --no-startup-id wl-paste --watch cliphist store

# Notification daemon
exec --no-startup-id swaync

# Alternating layouts script
exec --no-startup-id alternating_layouts.py

# Floating border script
exec --no-startup-id ~/.config/sway/utils/floating_border.py
